development:
  adapter: postgresql
  encoding: unicode
  database: copisteria_development
  pool: 5
  username: enrico
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: copisteria_test
  pool: 5
  username: enrico
  password:
